production:
  basic_auth_id: <%= ENV["BASIC_AUTH_USER"] %>
  basic_auth_password: <%= ENV["BASIC_AUTH_PASSWORD"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>